# Generated by Django 4.1 on 2022-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_myinfo_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='pincode',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
