# Generated by Django 4.1 on 2022-08-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_myinfo_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontAwsIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
