# Generated by Django 4.1 on 2022-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_fontawsicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('score_name', models.CharField(blank=True, max_length=50, null=True)),
                ('score_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
