# Generated by Django 4.1 on 2022-08-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_education_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='img',
            field=models.ImageField(default='img/vit.png', upload_to='media/'),
        ),
    ]
