# Generated by Django 4.1 on 2022-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_education_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(default='img/vit.png', upload_to=''),
        ),
    ]
