# Generated by Django 4.1 on 2022-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_education_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('comapny', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(default='img/vit.png', upload_to='')),
            ],
        ),
    ]
