# Generated by Django 4.1 on 2022-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
