# Generated by Django 4.1 on 2022-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_education_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
