# Generated by Django 4.1 on 2022-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_testimonial_desg'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
