# Generated by Django 4.1 on 2022-08-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_testimonial_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='slidertext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
