# Generated by Django 4.1 on 2022-08-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='insta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
